### PR TITLE
Front end design

### PR DESCRIPTION
**Pull request by cooperrholmes**
Front-end designed using HTML, CSS, and Bootstrap 5. Button prompts user to select .slp file. Modified CSS for drop shadows and button design. Will add JavaScript drag and drop functionality soon for file selection.

### CODE REVIEW

**Comment by Snaacky** [comment]
Rename `funnybutton` to a more descriptive ID. Remove the empty `logo` element in the CSS. Remove the empty `footer` tags in the index.

**Comment by Snaacky** [comment]
Remove footer and then looks good to me.

**Comment by cooperrholmes** [comment]
Added empty footer back because the site breaks without it.

**Comment by Snaacky** [comment]
Will fix later. Thanks.

**Pull request merged**
